#code to generate plot1.png
consomation <- read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors=FALSE)
consomation$Date=strptime(consomation$Date, format="%d/%m/%Y")
consomation$Global_active_power=as.numeric(consomation$Global_active_power)
consomation$Global_intensity=as.numeric(consomation$Global_intensity)
consomation$Global_reactive_power=as.numeric(consomation$Global_reactive_power)
consomation$Sub_metering_1=as.numeric(consomation$Sub_metering_1)
consomation$Sub_metering_2=as.numeric(consomation$Sub_metering_2)
consomation$Sub_metering_3=as.numeric(consomation$Sub_metering_3)
consomation$Voltage=as.numeric(consomation$Voltage)
consomation=subset(consomation,consomation$Date>as.POSIXlt("2007-01-31") & consomation$Date<as.POSIXlt("2007-02-03"))
png(file="plot1.png",width=480,height=480)
hist(consomation$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()
